/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IDE.java
 *
 * Created on 21/03/2010, 23:20:16
 */

package mazegen;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.HashSet;
import java.util.Set;
import java.util.Stack;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.Timer;

import graph.Colores;
import graph.MazeObj;

/**
 *
 * @author manusoftar
 */
public class IDE extends javax.swing.JFrame implements ActionListener, MouseMotionListener {

    /** Creates new form IDE */
    public IDE() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private boolean generando = false;
    private int ancho=15,alto=15,delay=15,cellsize=20;
    private Config cnf;
    private FirstPersonView firstPersonView = null;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mazeGRID1 = new graph.MazeGRID();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manusoftar� - MazeGen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        mazeGRID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        mazeGRID1.setAncho(19);
        mazeGRID1.setFocusable(true);
        mazeGRID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                System.out.println("MazeGRID keyPressed - evt.getKeyCode(): " + evt.getKeyCode());
                formKeyPressed(evt);
                mazeGRID1.requestFocusInWindow();
            }
        });

        javax.swing.GroupLayout mazeGRID1Layout = new javax.swing.GroupLayout(mazeGRID1);
        mazeGRID1.setLayout(mazeGRID1Layout);
        mazeGRID1Layout.setHorizontalGroup(
            mazeGRID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        mazeGRID1Layout.setVerticalGroup(
            mazeGRID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Nuevo");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cargar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Guardar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        JMenu jm = new JMenu();
        jm.setText("Exportar como texto");
        
        JMenuItem jmi1 = new JMenuItem("Simple");
        jmi1.addActionListener(this);
        jm.add(jmi1);
        JMenuItem jmi2 = new JMenuItem("Detallado");
        jmi2.addActionListener(this);
        jm.add(jmi2);
        //jmi.addActionListener(this);
        
        jMenu1.add(jm);
        
        jMenuItem5.setText("SALIR");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Configuraci\u00F3n");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem10.setText("Colores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laberinto");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenu4.setText("Algoritmos");

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("DFS");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem2);

        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("DFS2");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem3);

        jMenuItem11.setText("Probabilidad DFS2");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("Crawling Snake");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.getAccessibleContext().setAccessibleName("jRadioButtonMenuItem2");

        jMenu3.add(jMenu4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Generar nuevo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Abortar generaci�n");
        jMenuItem8.setEnabled(false);
        jMenu3.add(jMenuItem8);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Resolver");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Mostrar Soluci�n");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);
        jMenu3.add(jSeparator1);

        jMenuItem9.setText("Exportar");
        jMenuItem9.setToolTipText("Exportar el laberinto igual como imagen");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Vista en Primera Persona (3D)");
        jMenuItem12.setToolTipText("Abrir vista en primera persona del laberinto");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        jsp = new JScrollPane(mazeGRID1);	
        
        mazeGRID1.addMouseMotionListener(this);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(new BorderLayout());
        /*layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );*/
        getContentPane().add(jsp, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private interface keys {
            static final int arriba = 38;
            static final int derecha = 39;
            static final int abajo = 40;
            static final int izquierda = 37;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        mazeGRID1.setPadre(this);
        mazeGRID1.setCellSize(20);
        mazeGRID1.setAlto(15);
        mazeGRID1.setAncho(15);
        mazeGRID1.rePintar(0);
        mazeGRID1.repaint();
        /*jSpinner1.setFocusable(false);
        jSpinner2.setFocusable(false);
        jSpinner3.setFocusable(false);
        jSpinner4.setFocusable(false);*/
        
        this.pack();
        mazeGRID1.requestFocusInWindow();
        Timer tm = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                   if (generando && !mazeGRID1.isBusy()){
                       //jButton1.setText("Generar");
                       jMenuItem8.setEnabled(false);
                       generando = false;
                   }
                   mazeGRID1.setSize(ancho*cellsize,alto*cellsize);
                   //IDE.this.pack();
            }
        });

        tm.start();
        

        //this.pack();
    }//GEN-LAST:event_formWindowOpened

    private void mazeGRID1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mazeGRID1KeyPressed
        System.out.println("mazeGRID1KeyPressed LLAMADO - evt.getKeyCode(): " + evt.getKeyCode());
        // TODO add your handling code here:
        //System.out.println("Tecla presionada: " + evt.getKeyCode());
        
    }//GEN-LAST:event_mazeGRID1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("formKeyPressed LLAMADO - evt.getKeyCode(): " + evt.getKeyCode());
        // TODO add your handling code here:
        //System.out.println("Tecla presionada: " + evt.getKeyCode());
        Point endpos = null;
    	switch (evt.getKeyCode()){
            case keys.arriba:
                                endpos = mazeGRID1.keyPressed(keys.arriba);
                                break;
            case keys.derecha:
                                endpos = mazeGRID1.keyPressed(keys.derecha);
                                break;
            case keys.abajo:
                                endpos = mazeGRID1.keyPressed(keys.abajo);
                                break;
            case keys.izquierda:
                                endpos = mazeGRID1.keyPressed(keys.izquierda);
                                break;

        }
    	
    	if (endpos!=null){
	    	Dimension size = jsp.getViewport().getExtentSize();
	    	Point posicion = jsp.getViewport().getViewPosition();
	    	
	    	int x,y;
	    	x = endpos.x;
	    	y = endpos.y;
	    	
	    	if (debuger==null){
                debuger = new Debug();
                debuger.setSize(300,300);
            }
            //debuger.setVisible(true);
            debuger.setHeadPos(endpos);
            // Devolver el foco al MazeGRID para seguir recibiendo eventos de teclado
            mazeGRID1.requestFocusInWindow();
	    	
	    	/*if (x>(posicion.x+size.width) || y > (posicion.y+size.height)){
	    		posicion = new Point(x+2,y+2);
	    		jsp.getViewport().setViewPosition(posicion);
	    	}
	    	
	    	if (x<posicion.x || y < posicion.y){
	    		posicion = new Point(Math.max(0, x-2), Math.max(0, y-2));
	    		jsp.getViewport().setViewPosition(posicion);
	    	}*/
	    	
	    	int maxx,maxy;
	    	maxx = mazeGRID1.getWidth() - jsp.getViewport().getWidth();
	    	maxy = mazeGRID1.getHeight() - jsp.getViewport().getHeight();
	    	
	    	while (x+6>posicion.x+size.width){	
	    		   posicion.x = Math.min(posicion.x+5, maxx);
	    		
	    	}
    	
	    	while (y+6>posicion.y+size.height){
	    			 posicion.y= Math.min(posicion.y+5, maxy);
	    	}
	    	
	    	while(x-2<posicion.x && posicion.x>1){
	    		  posicion.x-=3;
	    	}
	    	
	    	while(y-2<posicion.y && posicion.y>1){
	    		  posicion.y-=3;
	    	}
	    	
	    	jsp.getViewport().setViewPosition(new Point(posicion.x,posicion.y));	
    	}
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //if (cnf==null){
        cnf = new Config(ancho,alto,delay,cellsize);
        //}
        cnf.setPadre(this);
        cnf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CustomFileChooser CFS = new CustomFileChooser();
        String path = CFS.saveFile(new CustomFilter("mmf","Manusoftar� Maze File (*.mmf)"));
        if (mazeGRID1.saveMaze(path)){
            System.out.println("Archivo guardado!");
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CustomFileChooser CFS = new CustomFileChooser();
        String path = CFS.openFile(new CustomFilter("mmf","Manusoftar� Maze File (*.mmf)"));
        mazeGRID1.openMaze(path);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        String[] formatos = ImageIO.getWriterFormatNames();
        formatos = unique(formatos);
        CustomFileChooser cfc = new CustomFileChooser();
        CustomFilter[] filtros = new CustomFilter[formatos.length];
        for (int n=0; n<filtros.length; n++){
            filtros[n] = new CustomFilter(formatos[n].toUpperCase(),"Archivo de imagen (*." + formatos[n].toLowerCase()+")");
        }
        String expPath = cfc.saveFile(filtros);
        System.out.println(expPath);
        if (mazeGRID1.exportMaze(expPath)){
            System.out.println("Laberinto exportado como imagen exitosamente");
        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonMenuItem2.isSelected()){
            mazeGRID1.setAlgorithm(0);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonMenuItem1.isSelected()){
            mazeGRID1.setAlgorithm(2);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
            jMenuItem8.setEnabled(true);
            mazeGRID1.setAncho(ancho);
            mazeGRID1.setAlto(alto);
            mazeGRID1.setCellSize(cellsize);
            mazeGRID1.setDelay(delay);
            mazeGRID1.gen();
            generando = true;
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        mazeGRID1.abort();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        mazeGRID1.Solve();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        mazeGRID1.showSolution(jCheckBoxMenuItem1.isSelected());

    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    protected Colores getScreenColors(){
        return mazeGRID1.getScreenColors();
    }

    protected Colores getPrintColors(){
        return mazeGRID1.getPrintColors();
    }

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ColorConf cconf = new ColorConf(this);
        cconf.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonMenuItem3.isSelected()){
            mazeGRID1.setAlgorithm(1);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        int p=90;
        p=Integer.valueOf(JOptionPane.showInputDialog(null,"Ingrese un valor entre 1 y 100"));
        mazeGRID1.setProbability(p);

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // Abrir la vista en primera persona
        if (firstPersonView == null || !firstPersonView.isVisible()) {
            // Crear el objeto MazeObj con la información actual del laberinto
            MazeObj maze = new MazeObj(
                mazeGRID1.getAncho(),
                mazeGRID1.getAlto(),
                mazeGRID1.getCellSize(),
                mazeGRID1.tablero,
                mazeGRID1.getInit(),
                mazeGRID1.getFin(),
                mazeGRID1
            );
            
            firstPersonView = new FirstPersonView(maze);
            firstPersonView.setVisible(true);
        } else {
            // Si ya existe, actualizar el laberinto y traer al frente
            MazeObj maze = new MazeObj(
                mazeGRID1.getAncho(),
                mazeGRID1.getAlto(),
                mazeGRID1.getCellSize(),
                mazeGRID1.tablero,
                mazeGRID1.getInit(),
                mazeGRID1.getFin(),
                mazeGRID1
            );
            firstPersonView.updateMaze(maze);
            firstPersonView.toFront();
            firstPersonView.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    protected void updateScreenColors(Colores cl){
       mazeGRID1.updateScreenColors(cl);
    }

    protected void updatePrintColors(Colores cl){
        mazeGRID1.updatePrintColors(cl);
    }

    public static String[] unique(String[] strings) {
        Set set = new HashSet();
        for (int i=0; i<strings.length; i++) {
            String name = strings[i].toLowerCase();
            set.add(name);
        }
        return (String[])set.toArray(new String[0]);
    }

    /**
     *
     * @param al
     * @param an
     * @param del
     * @param cell
     */
    public void setDatos(int al, int an, int del, int cell){
           cellsize = cell;
           delay = del;
           ancho = an;
           alto = al;
           mazeGRID1.setDelay(del);
           setSize((ancho*cellsize)+48,(alto*cellsize)+102);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private graph.MazeGRID mazeGRID1;
    private JScrollPane jsp;
    private Debug debuger;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		CustomFileChooser cfc = new CustomFileChooser();
		cfc.addSaveFilter("txt", "Archivo de texto plano");
		String path = cfc.saveFile();
		if (path.length()>0){
			JMenuItem dummy = (JMenuItem)e.getSource();
			if (dummy.getText().equalsIgnoreCase("simple")){
				mazeGRID1.toTxt(path);
			} else {
				mazeGRID1.toPropperTxt(path);
			}
		}
	}

	@Override
	public void mouseDragged(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseMoved(MouseEvent arg0) {
		// TODO Auto-generated method stub
		if (debuger==null){
			debuger = new Debug();
			debuger.setSize(300,300);
			debuger.setVisible(true);
		}
		
		debuger.setMousePos(arg0.getPoint());
	}

}

class CustomFileChooser extends JFrame {

      private String Path="";
      //private int mode=0;
      private JFileChooser FileChooser = new JFileChooser();
      private boolean done=false, result;
      private Stack<CustomFilter> oFilters = new Stack();
      private Stack<CustomFilter> sFilters = new Stack();
      
      public CustomFileChooser(){
            FileChooser.addActionListener(alistener);
            FileChooser.setAccessory(new ImagePreview(FileChooser));
            this.add(FileChooser);
      }
      
      ActionListener alistener = new ActionListener(){
                    public void actionPerformed(ActionEvent e) {
                                if(e.getActionCommand().equals("ApproveSelection")){
                                    result=true;
                                } else {
                                    result=false;
                                }
                                done=true;
                    }

      };

      public String openFile(CustomFilter Filter){
             done=false;
             FileChooser.addChoosableFileFilter(Filter);
             FileChooser.showOpenDialog(this);
             while (!done){}
             if (result){
                return FileChooser.getSelectedFile().getPath();
             } else {
                return "";
             }
      }

      public String openFile(CustomFilter[] Filter){
             done=false;
             for (int n=0; n<Filter.length; n++){
                 FileChooser.addChoosableFileFilter(Filter[n]);
             }
             FileChooser.showOpenDialog(this);
             while (!done){}
             
             if (result){
                return FileChooser.getSelectedFile().getPath();
             } else {
                return "";
             }
      }

      public String saveFile(CustomFilter Filter){
             done=false;
             FileChooser.addChoosableFileFilter(Filter);
             FileChooser.showSaveDialog(this);
             while (!done){}
             if (result){
                 if (FileChooser.getSelectedFile().getPath().indexOf(".")==-1){
                    return FileChooser.getSelectedFile().getPath()+"."+((CustomFilter)FileChooser.getFileFilter()).getMyExt().toLowerCase();
                 } else {
                    return FileChooser.getSelectedFile().getPath();
                 }
             } else {
                return "";
             }
      }

      public String saveFile(CustomFilter[] Filter){
             done=false;
             for (int n=0; n<Filter.length; n++){
                 FileChooser.addChoosableFileFilter(Filter[n]);
             }
             FileChooser.showSaveDialog(this);
             while (!done){}
             //System.out.println("Extensi�n: " + ((CustomFilter)FileChooser.getFileFilter()).getMyExt());
             if (result){
                if (FileChooser.getSelectedFile().getPath().indexOf(".")==-1){
                   return FileChooser.getSelectedFile().getPath()+"."+((CustomFilter)FileChooser.getFileFilter()).getMyExt().toLowerCase();
                } else {
                   return FileChooser.getSelectedFile().getPath();
                }
             } else {
                return "";
             }
      }
      
      /**
       * Muestra el dialogo de abrir archivo sin utilizar filtros de extensi�n, o bien habiendolos agregado al objeto mediante el 
       * m�todo addFilter()
       * @return
       */
      public String openFile(){
             CustomFilter[] ocfs = new CustomFilter[oFilters.size()];
             for (int n=0; n<oFilters.size(); n++){
                  ocfs[n]=oFilters.get(n);
             }
             return openFile(ocfs);
      }

      /**
       * Muestra el dialogo de guardar archivo sin utilizar filtros de extensi�n, o bien habiendolos agregado al objeto mediante el
       * m�todo addFilter()
       * @return
       */
      public String saveFile(){
             CustomFilter[] scfs = new CustomFilter[sFilters.size()];
             for (int n=0; n<sFilters.size(); n++){
                 scfs[n]=sFilters.get(n);
             }
             return saveFile(scfs);
      }
      
      
      /**
       * Agrega al objeto uno o m�s filtros para el di�logo de abrir...
       * @param ext
       * @param desc
       */
      public void addOpenFilter(String ext, String desc){
             
			 if (oFilters.search(new CustomFilter(ext,desc))==-1){
                 oFilters.push(new CustomFilter(ext,desc));
             }
      }


      /**
       * Agrega al objeto uno o m�s filtros para el di�logo de guardar...
       * @param ext
       * @param desc
       */
      public void addSaveFilter(String ext, String desc){
             if (sFilters.search(new CustomFilter(ext,desc))==-1){
                 sFilters.push(new CustomFilter(ext,desc));
             }
      }

}